//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FidesOS.Excecao {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMensagensExcecao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMensagensExcecao() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FidesOS.Excecao.ResourceMensagensExcecao", typeof(ResourceMensagensExcecao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código inválido..
        /// </summary>
        public static string CODIGO_INVALIDO {
            get {
                return ResourceManager.GetString("CODIGO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário um código para repor a sua palavra-passe..
        /// </summary>
        public static string CODIGO_REQUERIDO_PARA_ALTERAR_SENHA {
            get {
                return ResourceManager.GetString("CODIGO_REQUERIDO_PARA_ALTERAR_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O agendamento precisa ser feito com pelo menos 3 horas de antecedência..
        /// </summary>
        public static string DATA_INFERIOR_3_HORAS {
            get {
                return ResourceManager.GetString("DATA_INFERIOR_3_HORAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data é obrigatória e não pode estar vazia..
        /// </summary>
        public static string DATA_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível agendar para datas passadas. Escolha uma data futura..
        /// </summary>
        public static string DATA_NO_PASSADO {
            get {
                return ResourceManager.GetString("DATA_NO_PASSADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição é obrigatório..
        /// </summary>
        public static string DESCRICAO_INVALIDA {
            get {
                return ResourceManager.GetString("DESCRICAO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O correio eletrónico não pode estar vazio..
        /// </summary>
        public static string EMAIL_EM_BRANCO {
            get {
                return ResourceManager.GetString("EMAIL_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail já registado na plataforma.
        /// </summary>
        public static string EMAIL_EXISTENTE {
            get {
                return ResourceManager.GetString("EMAIL_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O correio eletrónico é inválido..
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail e/ou palavra-passe inválidos..
        /// </summary>
        public static string EMAIL_OU_SENHA_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_OU_SENHA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Empresa não encontrado..
        /// </summary>
        public static string EMPRESA_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("EMPRESA_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro desconhecido..
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código expirou..
        /// </summary>
        public static string EXPIRADO_CODIGO {
            get {
                return ResourceManager.GetString("EXPIRADO_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A sua sessão expirou. Inicie sessão novamente para continuar..
        /// </summary>
        public static string EXPIRADO_SESSAO {
            get {
                return ResourceManager.GetString("EXPIRADO_SESSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A palavra-passe deve ter mais de 6 caracteres..
        /// </summary>
        public static string INVALIDO_SENHA {
            get {
                return ResourceManager.GetString("INVALIDO_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível encontrar uma sessão válida. Inicie sessão para aceder a esta funcionalidade..
        /// </summary>
        public static string INVALIDO_SESSAO {
            get {
                return ResourceManager.GetString("INVALIDO_SESSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não encontrado..
        /// </summary>
        public static string NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome não pode estar vazio..
        /// </summary>
        public static string NOME_EM_BRANCO {
            get {
                return ResourceManager.GetString("NOME_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O perfil não foi informado..
        /// </summary>
        public static string PERFIL_NAO_INFORMADO {
            get {
                return ResourceManager.GetString("PERFIL_NAO_INFORMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O pedido não tem token..
        /// </summary>
        public static string SEM_TOKEN {
            get {
                return ResourceManager.GetString("SEM_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha informada é diferente da senha atual..
        /// </summary>
        public static string SENHA_ATUAL_DIFERENTE_DA_ATUAL {
            get {
                return ResourceManager.GetString("SENHA_ATUAL_DIFERENTE_DA_ATUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A palavra-passe não pode estar vazia..
        /// </summary>
        public static string SENHA_EM_BRANCO {
            get {
                return ResourceManager.GetString("SENHA_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não tem permissão para aceder a este recurso..
        /// </summary>
        public static string USUARIO_SEM_PERMISSAO_ACESSAR_RECURSO {
            get {
                return ResourceManager.GetString("USUARIO_SEM_PERMISSAO_ACESSAR_RECURSO", resourceCulture);
            }
        }
    }
}
